export const unifiedIndexes: { index: number; name: string }[] = [
	{ index: 1, name: 'Aceites' },
	{ index: 2, name: 'Acero de Construcción Liso' },
	{ index: 3, name: 'Acero de Construcción Corrugado' },
	{ index: 4, name: 'Agregado Fino' },
	{ index: 5, name: 'Agregado Grueso' },
	{ index: 6, name: 'Alambre y Cable de Cobre Desnudo' },
	{ index: 7, name: 'Alambre y Cable TW y THW' },
	{ index: 8, name: 'Alambre y Cable Tipo WP' },
	{ index: 9, name: 'Alcantarilla Metálica' },
	{ index: 10, name: 'Aparatos Sanitarios con Grifería' },
	{ index: 11, name: 'Artefacto de Alumbrado Exterior' },
	{ index: 12, name: 'Artefacto de Alumbrado Interior' },
	{ index: 13, name: 'Asfalto' },
	{ index: 14, name: 'Baldosa Acústica' },
	{ index: 16, name: 'Baldosa Vinílica' },
	{ index: 17, name: 'Bloques y Ladrillos' },
	{ index: 18, name: 'Cables Telefónicos' },
	{ index: 19, name: 'Cables Tipo NYY - N2XY' },
	{ index: 20, name: 'Cemento Asfáltico' },
	{ index: 21, name: 'Cemento Portland Tipo I' },
	{ index: 22, name: 'Cemento Portland Tipo II' },
	{ index: 23, name: 'Cemento Portland Tipo V' },
	{ index: 24, name: 'Cerámicas Esmaltadas y Sin Esmaltar' },
	{ index: 26, name: 'Cerrajería Nacional' },
	{ index: 27, name: 'Detonante' },
	{ index: 28, name: 'Dinamita' },
	{ index: 30, name: 'Dólar más Inflación del Mercado USA' },
	{ index: 31, name: 'Ducto de Concreto' },
	{ index: 32, name: 'Flete Terrestre' },
	{ index: 33, name: 'Flete Aéreo' },
	{ index: 34, name: 'Gasolina' },
	{ index: 37, name: 'Herramienta Manual' },
	{ index: 38, name: 'Hormigón' },
	{ index: 39, name: 'Índice General de Precios al Consumidor' },
	{ index: 40, name: 'Loseta' },
	{ index: 41, name: 'Madera en Tiras para Piso' },
	{ index: 42, name: 'Madera Importada para Encofrado y Carpintería' },
	{ index: 43, name: 'Madera Nacional para Encofrado y Carpintería' },
	{ index: 44, name: 'Madera Terciada para Encofrado y Carpintería' },
	{ index: 45, name: 'Madera Terciada para Encofrado' },
	{ index: 46, name: 'Malla de Acero' },
	{ index: 47, name: 'Mano de Obra' },
	{ index: 48, name: 'Maquinaria y Equipo Nacional' },
	{ index: 49, name: 'Maquinaria y Equipo Importado' },
	{ index: 50, name: 'Marco y Tapa de Fierro Fundido' },
	{ index: 51, name: 'Perfil de Acero Liviano' },
	{ index: 52, name: 'Perfil de Aluminio' },
	{ index: 53, name: 'Petróleo Diesel' },
	{ index: 54, name: 'Pintura Látex' },
	{ index: 55, name: 'Pintura Temple' },
	{ index: 56, name: 'Plancha de Acero LAC' },
	{ index: 57, name: 'Plancha de Acero LAF' },
	{ index: 59, name: 'Plancha de Fibro - Cemento' },
	{ index: 60, name: 'Plancha de Poliuretano' },
	{ index: 61, name: 'Plancha Galvanizada' },
	{ index: 62, name: 'Poste de Concreto' },
	{ index: 64, name: 'Terrazo' },
	{ index: 65, name: 'Tubería de Acero Negro y/o Galvanizado' },
	{ index: 66, name: 'Tubería de PVC para Red de Agua Potable y Alcantarillado' },
	{ index: 68, name: 'Tubería de Cobre' },
	{ index: 69, name: 'Tubería de Concreto Simple' },
	{ index: 70, name: 'Tubería de Concreto Reforzado' },
	{ index: 71, name: 'Tubería de Fierro Fundido' },
	{ index: 72, name: 'Tubería de PVC' },
	{ index: 73, name: 'Ductos Telefónicos de PVC' },
	{ index: 77, name: 'Válvula de Bronce Nacional' },
	{ index: 78, name: 'Válvula de Fierro Fundido Nacional' },
	{ index: 80, name: 'Concreto Premezclado' }
]
